#!/usr/bin/env bash

bash encoder_scripts/generate_explanations_race_test.sh
bash encoder_scripts/generate_explanations_religion_test.sh
bash encoder_scripts/generate_explanations_gender_test.sh

bash encoder_scripts/generate_explanations_race_val.sh
bash encoder_scripts/generate_explanations_religion_val.sh
bash encoder_scripts/generate_explanations_gender_val.sh