#!/usr/bin/env bash

bash decoder_scripts_jigsaw/generate_explanations_race_test.sh
bash decoder_scripts_jigsaw/generate_explanations_religion_test.sh
bash decoder_scripts_jigsaw/generate_explanations_gender_test.sh