#!/usr/bin/env bash

bash decoder_scripts_jigsaw/compute_fairness_race_test.sh
bash decoder_scripts_jigsaw/compute_fairness_religion_test.sh
bash decoder_scripts_jigsaw/compute_fairness_gender_test.sh