#!/usr/bin/env bash

bash encoder_scripts_jigsaw/generate_explanations_race_test.sh
bash encoder_scripts_jigsaw/generate_explanations_religion_test.sh
bash encoder_scripts_jigsaw/generate_explanations_gender_test.sh