#!/usr/bin/env bash

bash encoder_scripts_jigsaw/compute_fairness_race_test.sh
bash encoder_scripts_jigsaw/compute_fairness_religion_test.sh
bash encoder_scripts_jigsaw/compute_fairness_gender_test.sh
